version: 2.1
orbs:
 node: circleci/node@2.1.0
jobs:
 build-and-test:
 build:
 executor:
 name: node/default
 steps:
 - checkout

 test1:
       executor: 
      name: node/default
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
    test2:
     executor: 
      name: node/default
    - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - build-and-test
        test1:
        reguires:
          -build-and-test
          test2:
          requires:
          -build-and-test
